apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"addonmanager.kubernetes.io/mode":"EnsureExists"},"managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}},"f:labels":{".":{},"f:addonmanager.kubernetes.io/mode":{}}}},"manager":"kubectl","operation":"Update","time":"2020-05-01T14:22:33Z"}],"name":"tcp-services","namespace":"kube-system","selfLink":"/api/v1/namespaces/kube-system/configmaps/tcp-services"}}
  creationTimestamp: null
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:addonmanager.kubernetes.io/mode: {}
    manager: kubectl
    operation: Update
    time: "2020-05-01T14:22:33Z"
  name: tcp-services
  selfLink: /api/v1/namespaces/kube-system/configmaps/tcp-services
