apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","app":"helm","kubernetes.io/minikube-addons":"helm","name":"tiller"},"name":"tiller-deploy","namespace":"kube-system"},"spec":{"ports":[{"name":"tiller","port":44134,"protocol":"TCP","targetPort":"tiller"}],"selector":{"app":"helm","name":"tiller"},"type":"ClusterIP"}}
  creationTimestamp: null
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    app: helm
    kubernetes.io/minikube-addons: helm
    name: tiller
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:addonmanager.kubernetes.io/mode: {}
          f:app: {}
          f:kubernetes.io/minikube-addons: {}
          f:name: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":44134,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
          f:name: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl
    operation: Update
    time: "2020-05-01T14:22:47Z"
  name: tiller-deploy
  selfLink: /api/v1/namespaces/kube-system/services/tiller-deploy
spec:
  ports:
  - name: tiller
    port: 44134
    protocol: TCP
    targetPort: tiller
  selector:
    app: helm
    name: tiller
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
